//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tripwire.Web.Resources.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT US.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.infragistics.com/about-us/contact-us/.
        /// </summary>
        public static string Contact_UsURL {
            get {
                return ResourceManager.GetString("Contact_UsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Trial.
        /// </summary>
        public static string Download_Trial {
            get {
                return ResourceManager.GetString("Download_Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears you are trying open up a page that doesn&apos;t exist..
        /// </summary>
        public static string Error_404_Message {
            get {
                return ResourceManager.GetString("Error_404_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string Error_404_Page_Title {
            get {
                return ResourceManager.GetString("Error_404_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears the server has encountered an error..
        /// </summary>
        public static string Error_500_Message {
            get {
                return ResourceManager.GetString("Error_500_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string Error_500_Page_Title {
            get {
                return ResourceManager.GetString("Error_500_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve made a note of it on our side, but for now perhaps you&apos;d like to take a look at the table of contents, do a search or return to the &lt;a href=&quot;{0}&quot;&gt;home page&lt;/a&gt;?.
        /// </summary>
        public static string Error_Common_Format {
            get {
                return ResourceManager.GetString("Error_Common_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry but this site requires JavaScript..
        /// </summary>
        public static string Error_NoJS_Message {
            get {
                return ResourceManager.GetString("Error_NoJS_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version that you requested is unavailable. We&apos;ve redirected you to the latest version of the help..
        /// </summary>
        public static string Error_NoSuchVersion {
            get {
                return ResourceManager.GetString("Error_NoSuchVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page has encountered an error. We&apos;ve attempted to send the information to the server..
        /// </summary>
        public static string Error_OnPage_Message {
            get {
                return ResourceManager.GetString("Error_OnPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} your feedback on this topic.
        /// </summary>
        public static string Feedback_Format {
            get {
                return ResourceManager.GetString("Feedback_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpFeedback@infragistics.com.
        /// </summary>
        public static string FeedbackEmail {
            get {
                return ResourceManager.GetString("FeedbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET HELP.
        /// </summary>
        public static string Get_Help {
            get {
                return ResourceManager.GetString("Get_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.infragistics.com/help/.
        /// </summary>
        public static string Get_HelpURL {
            get {
                return ResourceManager.GetString("Get_HelpURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Topics.
        /// </summary>
        public static string Help_Topics {
            get {
                return ResourceManager.GetString("Help_Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.infragistics.com.
        /// </summary>
        public static string IG_Website {
            get {
                return ResourceManager.GetString("IG_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest.
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGAL INFORMATION.
        /// </summary>
        public static string Legal_Information {
            get {
                return ResourceManager.GetString("Legal_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.infragistics.com/legal/legal-information/.
        /// </summary>
        public static string Legal_InformationURL {
            get {
                return ResourceManager.GetString("Legal_InformationURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LICENSE AGREEMENT.
        /// </summary>
        public static string License_Agreement {
            get {
                return ResourceManager.GetString("License_Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.infragistics.com/legal/license/.
        /// </summary>
        public static string License_AgreementURL {
            get {
                return ResourceManager.GetString("License_AgreementURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEET US.
        /// </summary>
        public static string Meet_Us {
            get {
                return ResourceManager.GetString("Meet_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.infragistics.com/about-us/.
        /// </summary>
        public static string Meet_UsURL {
            get {
                return ResourceManager.GetString("Meet_UsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Navigation.
        /// </summary>
        public static string NavHide_Label {
            get {
                return ResourceManager.GetString("NavHide_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Navigation.
        /// </summary>
        public static string NavShow_Label {
            get {
                return ResourceManager.GetString("NavShow_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results Found.
        /// </summary>
        public static string NoResults_Message {
            get {
                return ResourceManager.GetString("NoResults_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops....
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIVACY AGREEMENT.
        /// </summary>
        public static string Privacy_Agreement {
            get {
                return ResourceManager.GetString("Privacy_Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.infragistics.com/legal/privacy/.
        /// </summary>
        public static string Privacy_AgreementURL {
            get {
                return ResourceManager.GetString("Privacy_AgreementURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        public static string Search_APITabName {
            get {
                return ResourceManager.GetString("Search_APITabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics.
        /// </summary>
        public static string Search_Topics {
            get {
                return ResourceManager.GetString("Search_Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/apiCollectionEn.
        /// </summary>
        public static string SearchAPICollection_Format {
            get {
                return ResourceManager.GetString("SearchAPICollection_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/collection1.
        /// </summary>
        public static string SearchCollection_Format {
            get {
                return ResourceManager.GetString("SearchCollection_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SITE MAP.
        /// </summary>
        public static string Site_Map {
            get {
                return ResourceManager.GetString("Site_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.infragistics.com/sitemap/.
        /// </summary>
        public static string Site_MapURL {
            get {
                return ResourceManager.GetString("Site_MapURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened....
        /// </summary>
        public static string Something_Happened {
            get {
                return ResourceManager.GetString("Something_Happened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try it now.
        /// </summary>
        public static string Try_It_Now {
            get {
                return ResourceManager.GetString("Try_It_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The topic you selected is only available in the latest version of our help documentation and you had selected to view an earlier version..
        /// </summary>
        public static string UpVersion_Latest {
            get {
                return ResourceManager.GetString("UpVersion_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Please note&lt;/strong&gt;, if you click on the link below you will be viewing the help in a later version than what you may have previously selected..
        /// </summary>
        public static string UpVersion_Note {
            get {
                return ResourceManager.GetString("UpVersion_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may have reached this page though a search or by trying to view a new topic in an earlier version of the help..
        /// </summary>
        public static string UpVersion_Reason {
            get {
                return ResourceManager.GetString("UpVersion_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View on.
        /// </summary>
        public static string View_on {
            get {
                return ResourceManager.GetString("View_on", resourceCulture);
            }
        }
    }
}
