//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Xamarin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Xamarin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tripwire.Web.Resources.Xamarin", typeof(Xamarin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/infragistics/xamarin-docs-en.
        /// </summary>
        public static string GitHub_link {
            get {
                return ResourceManager.GetString("GitHub_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infragistics Xamarin.Forms.
        /// </summary>
        public static string Home_Link {
            get {
                return ResourceManager.GetString("Home_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /products/ultimate.
        /// </summary>
        public static string MainSite_DownloadPath {
            get {
                return ResourceManager.GetString("MainSite_DownloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /products/xamarin.
        /// </summary>
        public static string MainSite_ProductPath {
            get {
                return ResourceManager.GetString("MainSite_ProductPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Infragistics Xamarin.Forms™ Help.
        /// </summary>
        public static string PageTitle_Format {
            get {
                return ResourceManager.GetString("PageTitle_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin.
        /// </summary>
        public static string ProductFamilyName {
            get {
                return ResourceManager.GetString("ProductFamilyName", resourceCulture);
            }
        }
    }
}
